### ISSUE TITLE
Can device discovery be cancelled?

### ISSUE THREAD

**Issue by pkozul** [pybluez/pybluez#158]
From what I can tell, the DeviceDiscoverer is not implemented in the Windows version. I was hoping to use the DeviceDiscoverer because it supports cancelling the inquiry.

Using the discover_devices() function to kick of discovery, is there a way to cancel the discovery?

**Comment by muelli** [comment]
This is also interesting for us.

**Comment by muelli** [comment]
this is pathetic.

**Comment by rgov** [comment]
@muelli I don't know how we can be more clear about it. No one is developing PyBluez. It says it in the README, it says it when you file an issue, the bot says it when no one responds.

It looks like from your GitHub history that you are a developer, so why don't you take a stab at implementing this? The maintainers can do a code review and merge it in for you.

If you would rather not spend time developing features for PyBluez, that's fine—neither does anyone else, which is why no one does. But please don't post "me too" comments to issues, especially derisive ones that don't help anyone.
