### ISSUE TITLE
Windows10

### ISSUE THREAD

**Issue by Newuser234** [pybluez/pybluez#177]
In windows 10, I have  the following error:
Could not find the windows platform SDK

**Comment by c-w** [comment]
You need to install `Visual C++ for Python` so that you can compile the C bindings for this library. The version of Visual C++ that is required varies based on your Python version: https://github.com/pybluez/pybluez/blob/98165617d05efe248fd3f374cc1787f810b70955/setup.py#L23-L34

There are more instructions on how to install the library on Windows here: https://github.com/pybluez/pybluez/issues/180#issuecomment-408235161
