### ISSUE TITLE
Installation Fails - System version of Python is 3.10

### ISSUE THREAD

**Issue by AidenSorabji** [pybluez/pybluez#437]
## System

 - **macOS Monterey 12.3:**
 - **MacBook Air:** (e.g., Raspberry Pi, external Bluetooth adaptor, etc.)
 - **3.10:**
 - **Latest Version of pybluez:**

## Issue

Installing fails, even with the system version of python being 3.10

**Comment by diego-rapoport** [comment]
Having the same problem. My log:

@ pip install pybluez
Collecting pybluez
  Using cached PyBluez-0.23.tar.gz (97 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in PyBluez setup command: use_2to3 is invalid.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

I'm on Arch Linux and my python version is also 3.10

**Comment by laurislopata** [comment]
Is there any news regarding this issue? Because I have the same problem with ArchLinux and python 3.10

**Comment by AidenSorabji** [comment]
> Is there any news regarding this issue? Because I have the same problem with ArchLinux and python 3.10

No, sadly

**Comment by PRO-2684** [comment]
Hopefully this will help u.
https://github.com/pybluez/pybluez/issues/438#issuecomment-1107701984

**Comment by dogtopus** [comment]
Unfortunately a lot has changed since the original codebase was developed and this project needs a heavy rewrite in order to fix a lot of issues, especially the BlueZ binding. The Windows binding should work on the dev branch as long as you install it from this repo. There's a macOS fix here #440 that needs testing so you could probably try it out. The longer term fix would be backporting the new macOS backend from pybluez2 but that requires time and a Mac to test the changes.

**Comment by dogtopus** [comment]
I merged #440, feel free to try again.
